name: thatismytype
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  provider: ^4.0.4
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  geoflutterfire: ^2.1.0
  firebase_storage: ^3.1.5
  cached_network_image: ^2.0.0
  multi_image_picker: ^4.6.5+rc.1
  animated_text_kit: ^2.0.0
  image_cropper: ^1.2.1
  flutter_svg: ^0.17.4
  font_awesome_flutter: ^8.8.1
  flutter_facebook_login: ^3.0.0
  page_transition: "^1.1.5"
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/

  fonts:
  - family: Playfair
    fonts:
      - asset: fonts/PlayfairDisplay-Regular.ttf
  - family: Martel
    fonts:
      - asset: fonts/Martel-Regular.ttf
  - family: Gothic
    fonts:
      - asset: fonts/GothicA1-Regular.ttf
  - family: Montserrat-regular
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
  - family: Josefin Sans
    fonts:
      - asset: fonts/JosefinSans-Light.ttf
  - family: Josefin Sans Bold
    fonts:
      - asset: fonts/JosefinSans-Bold.ttf
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Regular.ttf
  - family: Roboto Bold
    fonts:
      - asset: fonts/Roboto-Bold.ttf
  - family: Libre Baskerville
    fonts:
      - asset: fonts/LibreBaskerville-Bold.ttf
  - family: Karla-Bold
    fonts:
      - asset: fonts/Karla-Bold.ttf
  - family: Dancing Script
    fonts:
      - asset: fonts/DancingScript-Regular.ttf
  - family: Dancing Script
    fonts:
    - asset: fonts/Raleway-Regular.ttf
  - family: Gothic Semi-bold
    fonts:
    - asset: fonts/GothicA1-SemiBold.ttf


